Initial Countries parsing (#16)
* Fixed new error C7626 from VS2019 v16.6

* Read countries

* Missing changes from previous commit

* Function name fix

* commonItems update, tests for Country and Countries

* Restored typedef to structs

* Removed some debug logging

* Satisfying CodeFactor